# This file is currently a placeholder for potential funding sources
# If you find this project useful and would like to support its development,
# consider the following options:

github: 02ez

# Custom funding options
custom: ["https://github.com/sponsors", "https://buymeacoffee.com/simpleinterest"]

# Additional funding platforms (examples - update with actual accounts)
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username